# Shared prompt + detect helpers, sourced by install.sh (POSIX sh).
# No side effects on source; every function is pure except write_config, which
# writes the file it is given.

# Detect the Nix `system` double from `uname -sm`.
#   {aarch64,x86_64}-{darwin,linux}
detect_system() {
  _os=$(uname -s)
  _arch=$(uname -m)
  case "$_os" in
    Darwin) _plat=darwin ;;
    Linux)  _plat=linux ;;
    *) echo "unsupported OS: $_os" >&2; return 1 ;;
  esac
  case "$_arch" in
    arm64|aarch64) _cpu=aarch64 ;;
    x86_64|amd64)  _cpu=x86_64 ;;
    *) echo "unsupported architecture: $_arch" >&2; return 1 ;;
  esac
  printf '%s-%s\n' "$_cpu" "$_plat"
}

# True when we should prompt interactively (a tty exists and we were not told to
# run unattended). Non-interactive runs - curl | bash with no tty, or the test
# harness - accept every default silently.
_interactive() {
  [ "${DOTFILES_NONINTERACTIVE:-}" != "1" ] && [ -e /dev/tty ]
}

# prompt_default "Question" "default" -> chosen value on stdout.
# Press-enter (or non-interactive) accepts the default.
prompt_default() {
  _q="$1"
  _def="$2"
  if ! _interactive; then
    printf '%s\n' "$_def"
    return 0
  fi
  printf '%s [%s]: ' "$_q" "$_def" > /dev/tty
  IFS= read -r _ans < /dev/tty || _ans=""
  if [ -n "$_ans" ]; then
    printf '%s\n' "$_ans"
  else
    printf '%s\n' "$_def"
  fi
}

# Read an existing config.nix value (best-effort) so a re-run pre-fills its
# prompts with the current values. Prints nothing if the file/key is absent.
config_value() {
  _file="$1"
  _key="$2"
  [ -f "$_file" ] || return 0
  sed -n "s/^[[:space:]]*${_key}[[:space:]]*=[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p" "$_file" | head -n1
}

# write_config PATH USERNAME HOMEDIR DOTFILESDIR GITNAME GITEMAIL SYSTEM HOSTNAME HEADLESS
write_config() {
  cat > "$1" <<EOF
# config.nix - generated by install.sh. Commit this to YOUR fork. The flake
# ignores untracked files, so the installer runs \`git add -f config.nix\`.
# This is the ONLY file that differs between users/machines.
{
  username      = "$2";
  homeDirectory = "$3";
  dotfilesDir   = "$4";
  gitName       = "$5";
  gitEmail      = "$6";
  system        = "$7";
  hostname      = "$8";
  headless      = $9;
}
EOF
}
